packages:
  - packages/*
  - website
autoInstallPeers: true
catalogs:
  effect:
    "@effect/ai-anthropic": 4.0.0-beta.97
    "@effect/ai-openai": 4.0.0-beta.97
    "@effect/ai-openai-compat": 4.0.0-beta.97
    "@effect/ai-openrouter": 4.0.0-beta.97
    "@effect/atom-react": 4.0.0-beta.97
    "@effect/atom-solid": 4.0.0-beta.97
    "@effect/atom-vue": 4.0.0-beta.97
    "@effect/openapi-generator": 4.0.0-beta.97
    "@effect/opentelemetry": 4.0.0-beta.97
    "@effect/platform-browser": 4.0.0-beta.97
    "@effect/platform-bun": 4.0.0-beta.97
    "@effect/platform-node": 4.0.0-beta.97
    "@effect/platform-node-shared": 4.0.0-beta.97
    "@effect/sql-clickhouse": 4.0.0-beta.97
    "@effect/sql-d1": 4.0.0-beta.97
    "@effect/sql-libsql": 4.0.0-beta.97
    "@effect/sql-mssql": 4.0.0-beta.97
    "@effect/sql-mysql2": 4.0.0-beta.97
    "@effect/sql-pg": 4.0.0-beta.97
    "@effect/sql-pglite": 4.0.0-beta.97
    "@effect/sql-sqlite-bun": 4.0.0-beta.97
    "@effect/sql-sqlite-do": 4.0.0-beta.97
    "@effect/sql-sqlite-node": 4.0.0-beta.97
    "@effect/sql-sqlite-react-native": 4.0.0-beta.97
    "@effect/sql-sqlite-wasm": 4.0.0-beta.97
    "@effect/tsgo": ^0.19.0
    "@effect/vitest": 4.0.0-beta.97
    effect: 4.0.0-beta.97
  effectPeers:
    "@effect/ai-anthropic": ^4.0.0-beta.97
    "@effect/ai-openai": ^4.0.0-beta.97
    "@effect/ai-openai-compat": ^4.0.0-beta.97
    "@effect/ai-openrouter": ^4.0.0-beta.97
    "@effect/atom-react": ^4.0.0-beta.97
    "@effect/atom-solid": ^4.0.0-beta.97
    "@effect/atom-vue": ^4.0.0-beta.97
    "@effect/openapi-generator": ^4.0.0-beta.97
    "@effect/opentelemetry": ^4.0.0-beta.97
    "@effect/platform-browser": ^4.0.0-beta.97
    "@effect/platform-bun": ^4.0.0-beta.97
    "@effect/platform-node": ^4.0.0-beta.97
    "@effect/platform-node-shared": ^4.0.0-beta.97
    "@effect/sql-clickhouse": ^4.0.0-beta.97
    "@effect/sql-d1": ^4.0.0-beta.97
    "@effect/sql-libsql": ^4.0.0-beta.97
    "@effect/sql-mssql": ^4.0.0-beta.97
    "@effect/sql-mysql2": ^4.0.0-beta.97
    "@effect/sql-pg": ^4.0.0-beta.97
    "@effect/sql-pglite": ^4.0.0-beta.97
    "@effect/sql-sqlite-bun": ^4.0.0-beta.97
    "@effect/sql-sqlite-do": ^4.0.0-beta.97
    "@effect/sql-sqlite-node": ^4.0.0-beta.97
    "@effect/sql-sqlite-react-native": ^4.0.0-beta.97
    "@effect/sql-sqlite-wasm": ^4.0.0-beta.97
    "@effect/tsgo": ^0.16.2
    "@effect/vitest": ^4.0.0-beta.97
    effect: ^4.0.0-beta.97
configDependencies:
  "@savvy-web/pnpm-plugin-silk": 0.22.1+sha512-BCYsx9ezKBWsGGHPlE4WcEjgDX+5pNEnWsCa8Ud8VEiDKbpcjP8XeO8Iap1r3wmiHaQos5xQEKvDF3jblk4mWQ==
loglevel: info
overrides:
  typescript: ^7.0.0
